### ISSUE TITLE
the fact that the "im back" command stresses the c and k but not the a annoys me

### ISSUE THREAD

**Issue by superfloree** [feinwarusoftware/awesomobot-js#44]
it says "baccccckkk"
what is that bs
who stresses consonants like that
not only that u have the kkk in there and i call discrimination
"baaaaaaack" or be a pleb

**Comment by MattheousDT** [comment]
You not stressing the "B" either?? Discrimination bro...

**Comment by Dragon1320** [comment]
c a n c e r

**Comment by SuperFloree** [comment]
a b is also a consonant u dont stress consonants like that u try to sustain a b sound u cant its an implosive fix the command plebs
